/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appParticipantAnalyticsRouteImport } from './routes/(app)/participant-analytics'
import { Route as appOrganizerAnalyticsRouteImport } from './routes/(app)/organizer-analytics'
import { Route as appCreateRoomRouteImport } from './routes/(app)/create-room'
import { Route as appBattlesRouteImport } from './routes/(app)/battles'
import { Route as appAnalyticsRouteImport } from './routes/(app)/analytics'
import { Route as appAiAnalyticsRouteImport } from './routes/(app)/ai-analytics'
import { Route as appAdminAnalyticsRouteImport } from './routes/(app)/admin-analytics'
import { Route as appUsersUserIdRouteImport } from './routes/(app)/users/$userId'
import { Route as appRoomsRoomIdRouteImport } from './routes/(app)/rooms/$roomId'
import { Route as appBattlesBattleIdRouteImport } from './routes/(app)/battles/$battleId'
import { Route as appBattleAnalyticsBattleIdRouteImport } from './routes/(app)/battle-analytics.$battleId'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appParticipantAnalyticsRoute = appParticipantAnalyticsRouteImport.update({
  id: '/participant-analytics',
  path: '/participant-analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizerAnalyticsRoute = appOrganizerAnalyticsRouteImport.update({
  id: '/organizer-analytics',
  path: '/organizer-analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreateRoomRoute = appCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => appRouteRoute,
} as any)
const appBattlesRoute = appBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAiAnalyticsRoute = appAiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminAnalyticsRoute = appAdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersUserIdRoute = appUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => appRouteRoute,
} as any)
const appRoomsRoomIdRoute = appRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => appRouteRoute,
} as any)
const appBattlesBattleIdRoute = appBattlesBattleIdRouteImport.update({
  id: '/$battleId',
  path: '/$battleId',
  getParentRoute: () => appBattlesRoute,
} as any)
const appBattleAnalyticsBattleIdRoute =
  appBattleAnalyticsBattleIdRouteImport.update({
    id: '/battle-analytics/$battleId',
    path: '/battle-analytics/$battleId',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin-analytics': typeof appAdminAnalyticsRoute
  '/ai-analytics': typeof appAiAnalyticsRoute
  '/analytics': typeof appAnalyticsRoute
  '/battles': typeof appBattlesRouteWithChildren
  '/create-room': typeof appCreateRoomRoute
  '/organizer-analytics': typeof appOrganizerAnalyticsRoute
  '/participant-analytics': typeof appParticipantAnalyticsRoute
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appIndexRoute
  '/battle-analytics/$battleId': typeof appBattleAnalyticsBattleIdRoute
  '/battles/$battleId': typeof appBattlesBattleIdRoute
  '/rooms/$roomId': typeof appRoomsRoomIdRoute
  '/users/$userId': typeof appUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/admin-analytics': typeof appAdminAnalyticsRoute
  '/ai-analytics': typeof appAiAnalyticsRoute
  '/analytics': typeof appAnalyticsRoute
  '/battles': typeof appBattlesRouteWithChildren
  '/create-room': typeof appCreateRoomRoute
  '/organizer-analytics': typeof appOrganizerAnalyticsRoute
  '/participant-analytics': typeof appParticipantAnalyticsRoute
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appIndexRoute
  '/battle-analytics/$battleId': typeof appBattleAnalyticsBattleIdRoute
  '/battles/$battleId': typeof appBattlesBattleIdRoute
  '/rooms/$roomId': typeof appRoomsRoomIdRoute
  '/users/$userId': typeof appUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/admin-analytics': typeof appAdminAnalyticsRoute
  '/(app)/ai-analytics': typeof appAiAnalyticsRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/battles': typeof appBattlesRouteWithChildren
  '/(app)/create-room': typeof appCreateRoomRoute
  '/(app)/organizer-analytics': typeof appOrganizerAnalyticsRoute
  '/(app)/participant-analytics': typeof appParticipantAnalyticsRoute
  '/(app)/profile': typeof appProfileRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/battle-analytics/$battleId': typeof appBattleAnalyticsBattleIdRoute
  '/(app)/battles/$battleId': typeof appBattlesBattleIdRoute
  '/(app)/rooms/$roomId': typeof appRoomsRoomIdRoute
  '/(app)/users/$userId': typeof appUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin-analytics'
    | '/ai-analytics'
    | '/analytics'
    | '/battles'
    | '/create-room'
    | '/organizer-analytics'
    | '/participant-analytics'
    | '/profile'
    | '/login'
    | '/register'
    | '/'
    | '/battle-analytics/$battleId'
    | '/battles/$battleId'
    | '/rooms/$roomId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin-analytics'
    | '/ai-analytics'
    | '/analytics'
    | '/battles'
    | '/create-room'
    | '/organizer-analytics'
    | '/participant-analytics'
    | '/profile'
    | '/login'
    | '/register'
    | '/'
    | '/battle-analytics/$battleId'
    | '/battles/$battleId'
    | '/rooms/$roomId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(app)/admin-analytics'
    | '/(app)/ai-analytics'
    | '/(app)/analytics'
    | '/(app)/battles'
    | '/(app)/create-room'
    | '/(app)/organizer-analytics'
    | '/(app)/participant-analytics'
    | '/(app)/profile'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/'
    | '/(app)/battle-analytics/$battleId'
    | '/(app)/battles/$battleId'
    | '/(app)/rooms/$roomId'
    | '/(app)/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/participant-analytics': {
      id: '/(app)/participant-analytics'
      path: '/participant-analytics'
      fullPath: '/participant-analytics'
      preLoaderRoute: typeof appParticipantAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organizer-analytics': {
      id: '/(app)/organizer-analytics'
      path: '/organizer-analytics'
      fullPath: '/organizer-analytics'
      preLoaderRoute: typeof appOrganizerAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-room': {
      id: '/(app)/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof appCreateRoomRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/battles': {
      id: '/(app)/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof appBattlesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/ai-analytics': {
      id: '/(app)/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof appAiAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin-analytics': {
      id: '/(app)/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof appAdminAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/$userId': {
      id: '/(app)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof appUsersUserIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/rooms/$roomId': {
      id: '/(app)/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof appRoomsRoomIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/battles/$battleId': {
      id: '/(app)/battles/$battleId'
      path: '/$battleId'
      fullPath: '/battles/$battleId'
      preLoaderRoute: typeof appBattlesBattleIdRouteImport
      parentRoute: typeof appBattlesRoute
    }
    '/(app)/battle-analytics/$battleId': {
      id: '/(app)/battle-analytics/$battleId'
      path: '/battle-analytics/$battleId'
      fullPath: '/battle-analytics/$battleId'
      preLoaderRoute: typeof appBattleAnalyticsBattleIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appBattlesRouteChildren {
  appBattlesBattleIdRoute: typeof appBattlesBattleIdRoute
}

const appBattlesRouteChildren: appBattlesRouteChildren = {
  appBattlesBattleIdRoute: appBattlesBattleIdRoute,
}

const appBattlesRouteWithChildren = appBattlesRoute._addFileChildren(
  appBattlesRouteChildren,
)

interface appRouteRouteChildren {
  appAdminAnalyticsRoute: typeof appAdminAnalyticsRoute
  appAiAnalyticsRoute: typeof appAiAnalyticsRoute
  appAnalyticsRoute: typeof appAnalyticsRoute
  appBattlesRoute: typeof appBattlesRouteWithChildren
  appCreateRoomRoute: typeof appCreateRoomRoute
  appOrganizerAnalyticsRoute: typeof appOrganizerAnalyticsRoute
  appParticipantAnalyticsRoute: typeof appParticipantAnalyticsRoute
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
  appBattleAnalyticsBattleIdRoute: typeof appBattleAnalyticsBattleIdRoute
  appRoomsRoomIdRoute: typeof appRoomsRoomIdRoute
  appUsersUserIdRoute: typeof appUsersUserIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminAnalyticsRoute: appAdminAnalyticsRoute,
  appAiAnalyticsRoute: appAiAnalyticsRoute,
  appAnalyticsRoute: appAnalyticsRoute,
  appBattlesRoute: appBattlesRouteWithChildren,
  appCreateRoomRoute: appCreateRoomRoute,
  appOrganizerAnalyticsRoute: appOrganizerAnalyticsRoute,
  appParticipantAnalyticsRoute: appParticipantAnalyticsRoute,
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
  appBattleAnalyticsBattleIdRoute: appBattleAnalyticsBattleIdRoute,
  appRoomsRoomIdRoute: appRoomsRoomIdRoute,
  appUsersUserIdRoute: appUsersUserIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
